export const GET_GATEGORY = 'GET_GATEGORY';
export const CATEGORY_ERROR = 'CATEGORY_ERROR';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const PRODUCTS_ERROR = 'PRODUCTS_ERROR';

export const GET_PRODUCTS_BY_PARAMS = 'GET_PRODUCTS_BY_PARAMS';
export const GET_PRODUCTS_BY_PARAMS_ERROR = 'GET_PRODUCTS_BY_PARAMS_ERROR';


export const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';
export const SEARCH_PRODUCTS_ERROR = 'SEARCH_PRODUCTS_ERROR';
